# Generated by Django 4.0.1 on 2022-01-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_name', models.CharField(max_length=100)),
                ('task_description', models.TextField()),
                ('task_status', models.BooleanField(default=False)),
                ('task_due_date', models.DateTimeField(auto_now_add=True)),
                ('category', models.CharField(choices=[('OFFICE', 'Office'), ('MANUAL WORK', 'Manual work'), ('CODING', 'Coding')], max_length=30)),
            ],
        ),
    ]
